#pragma once

#include <drone_mapper/types/DroneTypes.h>
#include <drone_mapper/types/LidarTypes.h>
#include <drone_mapper/types/MapTypes.h>
#include <drone_mapper/types/MissionTypes.h>

#include <filesystem>
#include <string>
#include <tuple>
#include <vector>

namespace drone_mapper::types {

struct SimulationConfigData {
    std::filesystem::path map_filename{};
    PhysicalLength map_resolution{};
    Position3D map_offset{};
    Position3D initial_drone_position{};
    HorizontalAngle initial_angle{};
};

struct SimulationCompositionData {
    std::filesystem::path composition_file;
    std::vector<std::tuple<SimulationConfigData, std::vector<MissionConfigData>>> simulation_mission_groups;
    std::vector<DroneConfigData> drones;
    std::vector<LidarConfigData> lidars;
    std::vector<std::filesystem::path> simulation_source_files;
    std::vector<std::vector<std::filesystem::path>> mission_source_files_by_group;
    std::vector<std::filesystem::path> drone_source_files;
    std::vector<std::filesystem::path> lidar_source_files;
};

enum class ResolutionRequestStatus {
    Accepted,
    Ignored,
    IgnoredTooSmall,
};

struct SimulationResult {
    // Input configurations that produced this run; used later in the YAML report.
    SimulationConfigData simulation_config{};
    MissionConfigData mission_config{};
    DroneConfigData drone_config{};
    LidarConfigData lidar_config{};
    std::filesystem::path simulation_source_file{};
    std::filesystem::path mission_source_file{};
    std::filesystem::path drone_source_file{};
    std::filesystem::path lidar_source_file{};
    ResolutionRequestStatus resolution_request_status = ResolutionRequestStatus::Ignored;
    // Mission-level outcomes for this simulation run.
    std::vector<MissionRunResult> mission_results{};
    // Output map file generated by this run.
    std::filesystem::path output_map_file{};
    // Output-map geometry used for score calculation and reporting.
    MapConfig output_map_config; 
    // Score produced by comparing the hidden map with the output map.
    double mission_score = 0.0;
};

// Flat report: each entry represents one concrete simulation/mission/drone/lidar run.
struct SimulationManagerReport {
    std::string generated_at_utc{};
    std::string metric{};
    // Inclusive score range used by the report.
    std::tuple<double, double> score_range{};
    int error_score = -1;
    std::vector<SimulationResult> runs{};
};

} // namespace drone_mapper::types
